# POST http://localhost:3000/gameOver
# Content-Type: application/json

# {
#   "userId": "user_2ftUAudylKkitH5CeTy0hjpYtiq",
#   "score": 444
# }


# POST http://localhost:3000/register
# Content-Type: application/json

# {
#   "id": "user_2fhs3RLpFC28pCJT6lPe6e2jyp1",
#   "email": "pateld2@bxscience.edu"
# }


# POST http://localhost:3000/scores
# Content-Type: application/json

# {
#   "userId": "user_2ftUAudylKkitH5CeTy0hjpYtiq"
# }

GET http://localhost:3000/top-scores?length=90
Content-Type: application/json